image:
  repository: nginx 
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  port: 80
ingress:
  enabled: true
  className: "nginx"
  host: "test-api"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: "/"
  pathType: Prefix
